### ISSUE TITLE
[Bug] No active revocation registry for existing credential definition

### ISSUE THREAD

**Issue by esune** [bcgov/DITP#62] opened 2023-09-15 16:26 UTC
Existing credential definitions seem to end-up in a state where no active revocation registry is available, which causes issuance of new credentials to fail:
```
"error_msg": 
"Cred def id 6hChBFAutS7HvAqSHkENTL:3:CL:70263:test has no active revocation registry."
```

This is likely an issue in ACA-Py, but logging here for now to triage - we have observed it also in single-instance ACA-Py agents. We need to figure out how/why the agent is getting into this state. c.c.: @WadeBarnes @usingtechnology 

See this comment: https://github.com/bcgov/traction/pull/790#pullrequestreview-1628189123

**Comment by loneil** [comment] 2023-09-15 16:28
That case above was a new cred def actually though. And I can still do it fine on other 0.10.1 branches.

**Comment by WadeBarnes** [comment] 2023-09-15 16:30
This could be related to issues being fixed in `0.10.2`.

**Comment by esune** [comment] 2023-09-15 16:32
> This could be related to issues being fixed in `0.10.2`.

Wade beat me to it. @loneil I would track the issue here and assume it will be fixed with 0.10.2 - we could test using the rc/nightly image if we wanted a head start before publishing, but I think it is unrelated to @shaangill025's changes

**Comment by loneil** [comment] 2023-09-15 16:46
Yeah I don't know either I'm getting really (un)lucky, or it's specific to something in the 681 environment because I can't repro in any other 0.10.1 environment yet.

This is happening each time I try and create a def on 681 so far https://github.com/bcgov/traction/pull/790#issuecomment-1721544641

**Comment by usingtechnology** [comment] 2023-09-15 17:31
are you using the same tenant? if so, try a new tenant that has not been connected to the endorser.

**Comment by loneil** [comment] 2023-09-15 19:46
> are you using the same tenant? if so, try a new tenant that has not been connected to the endorser.

Yeah, steps to reproduce are

1 Create a new tenant
2 Make issuer (connect/register) for bcovrin-test, endorser Ket75eV5UQvVkW2XBjgDH7 
3 Create schema
4 Create revocable cred def
5 Issue it to BC Wallet and accept

On https://pr-790-traction-tenant-ui-dev.apps.silver.devops.gov.bc.ca/ (which is 0.10.1) this errors on step 3 and step 5 (see linked above)

On a different PR also 0.10.1 these steps succeed

And on dev, with an existing Tenant it also works.

So I'm doubtful this is specific to 0.10.1 rather than a specific set of changes there, unless I'm missing something? Or did the changes in PR 790 make us susceptible to this ACA-Py bug in a way we are not anywhere else?

**Comment by usingtechnology** [comment] 2023-09-15 19:57
see if you can find anything in the logs related to didexchange resolution... that's one of the bugs.

see [pr 2476](https://github.com/hyperledger/aries-cloudagent-python/pull/2476) / [issue 2475](https://github.com/hyperledger/aries-cloudagent-python/issues/2475)

**Comment by loneil** [comment] 2023-09-15 20:04
The error is when it's trying to upload Tails

```
2023-09-15 16:19:44,745 aries_cloudagent.core.event_bus ERROR Error occurred while processing event
Traceback (most recent call last):
File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/core/event_bus.py", line 121, in notify
await processor()
File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/revocation/routes.py", line 1581, in on_revocation_registry_endorsed_event
await registry_record.upload_tails_file(profile)
File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/revocation/models/issuer_rev_reg_record.py", line 446, in upload_tails_file
(upload_success, result) = await tails_server.upload_tails_file(
File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/tails/indy_tails_server.py", line 50, in upload_tails_file
pool = write_ledger[1].pool
TypeError: 'IndyVdrLedger' object is not subscriptable
```

does that use DID Exchange?

**Comment by usingtechnology** [comment] 2023-09-15 20:06
there is a bug @shaangill025 fixed... that write_ledger[1] is the issue... it's just write_ledger.pool.

**Comment by loneil** [comment] 2023-09-15 20:11
Ah ok, so then yeah we have to wait on 0.10.2 for the multi-ledger PR 790. Thanks.

**Comment by esune** [comment] 2023-09-18 16:23
We experienced this issue again today with the BC Wallet Showcase production instance. As it turns out, part of the problem was also the fact that the `tails` directory was not being persisted and therefore calls executed by different pods were failing due to missing tails file in the filesystem.

**Comment by esune** [comment] 2023-09-18 16:25
Moving to blocked, pending upgrades in the Traction chart and new ACA-Py image

**Comment by esune** [comment] 2023-09-20 20:03
@WadeBarnes do you think we can close this, given what we discovered and fixed (bug in aca-py, missing tails persistence)?

**Comment by WadeBarnes** [comment] 2023-09-20 20:05
Yes

**Closed** 2023-09-20 20:54 UTC
Labels: bug
